[package]
name = "kalamine"
version = "0.38.0"
edition = "2024"
description = "A cross-platform Keyboard Layout Maker"
authors = ["Fabien Cazenave <fabien@cazenave.cc>"]
license = "MIT"
repository = "https://github.com/OneDeadKey/kalamine"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
