//! Output a keyboard layout to Windows AHK representation
//! To be used by AutoHotKey v1.1: https://autohotkey.com

const std = @import("std");
const zg = @import("zg");
const graphemes = zg.graphemes;
// TODO:
// const Grapheme = graphemes.Grapheme;
const layout = @import("../layout.zig");
const KeyboardLayout = layout.KeyboardLayout;
const Layer = layout.Layer;
const KeyCode = layout.KeyCode;
const windows = @import("windows.zig");

pub fn writeLayout(
    writer: *std.Io.Writer,
    keyboard_layout: *const KeyboardLayout,
) !void {
    try writer.writeAll(ahk_v1_header_1);
    try writer.print(ahk_v1_header_2, .{keyboard_layout.name});
    try writer.writeAll(ahk_v1_header_3);
    try writeLayer(writer, keyboard_layout, .base);
    // TODO: kalamine/generators/ahk.py:113
    // TODO: kalamine/template.py:34

    if (keyboard_layout.hasAltgr()) {
        try writer.writeAll(ahk_v1_altgr_header);
        try writeLayer(writer, keyboard_layout, .altgr);
    }

    try writer.writeAll(ahk_v1_ctrl_header);
    try writer.writeAll("KALAMINE::SHORTCUTS\n"); // TODO:
}

fn writeLayer(
    writer: *std.Io.Writer,
    keyboard_layout: *const KeyboardLayout,
    // TODO: maybe a specific enum for base/altgr/ctrl/altgr?
    layer: Layer,
) !void {
    const base_layer, const shift_layer, const base_prefix, const shift_prefix =
        if (layer == .base)
            .{
                keyboard_layout.layers.get(.base).?,
                keyboard_layout.layers.get(.shift).?,
                " ",
                "+",
            }
        else if (!keyboard_layout.layers.contains(.altgr))
            return
        else
            .{
                keyboard_layout.layers.get(.altgr).?,
                keyboard_layout.layers.get(.altgr_shift).?,
                " <^>!",
                "<^>!+",
            };

    for (std.enums.values(KeyCode)) |key_name| {
        switch (key_name) {
            .ae01 => try writer.writeAll("; Digits\n\n"),
            .ad01 => try writer.writeAll("; Letters, first row\n\n"),
            .ac01 => try writer.writeAll("; Letters, second row\n\n"),
            .ab01 => try writer.writeAll("; Letters, third row\n\n"),
            .ae11 => try writer.writeAll("; Pinky keys\n\n"),
            .spce => try writer.writeAll("; Space bar\n\n"),
            // FIXME: ABNT / JIS keys: these two keys are not supported yet by kalamine
            .ae13, .ab11 => continue,
            else => {},
        }

        const sc = windows.scancode(key_name);

        try writeKey(writer, key_name, sc, base_prefix, base_layer);
        try writeKey(writer, key_name, sc, shift_prefix, shift_layer);
        try writer.writeAll("\n"); // TODO: too many spaces

        // TODO: kalamine/generators/ahk.py:59
        // TODO: big refactor to do with unshifted/shifted in the same layer
    }
}

fn writeKey(
    writer: *std.Io.Writer,
    key_name: KeyCode,
    sc: []const u8,
    prefix: []const u8,
    layer: std.AutoHashMapUnmanaged(KeyCode, []const u8),
) !void {
    if (layer.get(key_name)) |symbol| {
        const sym = ahkEscape(symbol);
        _ = sym;
        // TODO: kalamine/generators/ahk.py:59
        // if symbol == dead key

        var it = std.unicode.Utf8Iterator{
            .bytes = symbol,
            .i = 0,
        };
        const codepoint = it.nextCodepoint() orelse return;

        // TODO: actions/dead keys in JSON
        try writer.print("{s}SC{s}::SendKey(\"U+{x:0>4}\", {{}}) ; {s}\n", .{ prefix, sc, codepoint, symbol });
    }
}

fn ahkEscape(key: []const u8) void {
    if (graphemes.count(key) == 1) {
        // TODO:
    }
}

const ahk_v1_header_1 =
    \\; Generated by kalamine
    \\
    \\#NoEnv
    \\#Persistent
    \\#InstallKeybdHook
    \\#SingleInstance,       force
    \\#MaxThreadsBuffer
    \\#MaxThreadsPerHotKey   3
    \\#MaxHotkeysPerInterval 300
    \\#MaxThreads            20
    \\
    \\SendMode Event ; either Event or Input
    \\SetKeyDelay,   -1
    \\SetBatchLines, -1
    \\Process, Priority, , R
    \\SetWorkingDir, %A_ScriptDir%
    \\StringCaseSense, On
    \\
    \\
    \\;-------------------------------------------------------------------------------
    \\; On/Off Switch
    \\;-------------------------------------------------------------------------------
    \\
    \\global Active := True
    \\
    \\HideTrayTip() {
    \\  TrayTip  ; Attempt to hide it the normal way.
    \\  if SubStr(A_OSVersion,1,3) = "10." {
    \\    Menu Tray, NoIcon
    \\    Sleep 200  ; It may be necessary to adjust this sleep.
    \\    Menu Tray, Icon
    \\  }
    \\}
    \\
    \\ShowTrayTip() {
    \\
;

const ahk_v1_header_2 =
    \\  title := "{s}"
    \\
;

const ahk_v1_header_3 =
    \\  text := Active ? "ON" : "OFF"
    \\  HideTrayTip()
    \\  TrayTip, %title% , %text%, 1, 0x31
    \\  SetTimer, HideTrayTip, -1500
    \\}
    \\
    \\RAlt & Alt::
    \\Alt & RAlt::
    \\  global Active
    \\  Active := !Active
    \\  ShowTrayTip()
    \\  return
    \\
    \\#If Active
    \\SetTimer, ShowTrayTip, -1000  ; not working
    \\
    \\
    \\;-------------------------------------------------------------------------------
    \\; DeadKey Helpers
    \\;-------------------------------------------------------------------------------
    \\
    \\global DeadKey := ""
    \\
    \\; Check CapsLock status, upper the char if needed and send the char
    \\SendChar(char) {
    \\  if % GetKeyState("CapsLock", "T") {
    \\    if (StrLen(char) == 6) {
    \\      ; we have something in the form of `U+NNNN `
    \\      ; Change it to 0xNNNN so it can be passed to `Chr` function
    \\      char := Chr("0x" SubStr(char, 3, 4))
    \\    }
    \\    StringUpper, char, char
    \\  }
    \\  Send, {%char%}
    \\}
    \\
    \\DoTerm(base:="") {
    \\  global DeadKey
    \\
    \\  term := SubStr(DeadKey, 2, 1)
    \\
    \\  Send, {%term%}
    \\  SendChar(base)
    \\  DeadKey := ""
    \\}
    \\
    \\DoAction(action:="") {
    \\  global DeadKey
    \\
    \\  if (action == "U+0020") {
    \\    Send, {SC39}
    \\    DeadKey := ""
    \\  }
    \\  else if (StrLen(action) != 2) {
    \\    SendChar(action)
    \\    DeadKey := ""
    \\  }
    \\  else if (action == DeadKey) {
    \\    DoTerm(SubStr(DeadKey, 2, 1))
    \\  }
    \\  else {
    \\    DeadKey := action
    \\  }
    \\}
    \\
    \\SendKey(base, deadkeymap) {
    \\  if (!DeadKey) {
    \\    DoAction(base)
    \\  }
    \\  else if (deadkeymap.HasKey(DeadKey)) {
    \\    DoAction(deadkeymap[DeadKey])
    \\  }
    \\  else {
    \\    DoTerm(base)
    \\  }
    \\}
    \\
    \\
    \\;-------------------------------------------------------------------------------
    \\; Base
    \\;-------------------------------------------------------------------------------
    \\
    \\
;

const ahk_v1_altgr_header =
    \\
    \\;-------------------------------------------------------------------------------
    \\; AltGr
    \\;-------------------------------------------------------------------------------
    \\
    \\; Special Keys
    \\
    \\$<^>!Esc::       Send {SC01}
    \\$<^>!End::       Send {SC4f}
    \\$<^>!Home::      Send {SC47}
    \\$<^>!Delete::    Send {SC53}
    \\$<^>!Backspace:: Send {SC0e}
    \\
    \\
;

const ahk_v1_ctrl_header =
    \\
    \\;-------------------------------------------------------------------------------
    \\; Ctrl
    \\;-------------------------------------------------------------------------------
    \\
    \\
;
